### ISSUE TITLE
Why do I report an error?,I hope the author can give me an answer.

### ISSUE THREAD

**Issue by TPD100706** [findooshka/diffusion-atoms#1]
File "/home/u2023170613/diffusion-atoms-master/main.py", line 204, in main
    runner.train()
  File "/home/u2023170613/diffusion-atoms-master/runners/diffusion.py", line 177, in train
    loss = lattice_loss(model,
           ^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170613/diffusion-atoms-master/functions/losses.py", line 66, in lattice_loss
    noise_estimate = get_output(noised_atoms_batch, operations, space_group, sg_type, model, t, device, output_type="lattice", emax=-1)[1]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170613/diffusion-atoms-master/functions/atomic.py", line 228, in get_output
    graph, line_graph = get_graphs(noised_atoms[i], operations[i], device, t[i], lattice_system[i], sg_type[i])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170613/diffusion-atoms-master/functions/atomic.py", line 215, in get_graphs
    graph, line_graph = atom_dgl_multigraph(atoms=atoms, operations=operations)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170613/diffusion-atoms-master/functions/graph.py", line 143, in atom_dgl_multigraph
    u, v, r, sym = nearest_neighbor_edges(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170613/diffusion-atoms-master/functions/graph.py", line 95, in nearest_neighbor_edges
    assert np.abs(np.linalg.norm(inv_diff) - np.linalg.norm(neig_diff)) < 1e-3, "Inconsistent lattice / symmetry operations"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Inconsistent lattice / symmetry operation

**Comment by findooshka** [comment]
Thank you for reporting!

I managed to reproduce the error, it seems that the issue is due to numerical imprecision. I've increased the threshold in this assert, so it should be fine now.

Let me know if the issue persists.

**Comment by TPD100706** [comment]
> Thank you for reporting!
> 
> I managed to reproduce the error, it seems that the issue is due to numerical imprecision. I've increased the threshold in this assert, so it should be fine now.
> 
> Let me know if the issue persists.

**Comment by TPD100706** [comment]
Thanks a lot to the authors for their reply, I managed to reproduce the crystal generation part of the paper, but I ran into problems when I wanted to run the code for the evaluation section.
![7b94367918028b272d1f0891c6f943a](https://github.com/user-attachments/assets/d4fb7236-e40f-4922-8d8e-18984fb8d11d)
''prop_model_eval''Didn't find it.

**Comment by TPD100706** [comment]
Hello author, I very much hope you can answer my doubts,when I use the following command to sample generation, I found that the generated crystals only have a P 1 space group, for which I am very puzzled.
python3 main.py --config config.yml --doc pretrained --sample --sampling_order_path name_of_the_file
